//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class BoPhan : XPLiteObject
    {
        string fMaBP;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã bộ phận")]
        public string MaBP
        {
            get { return fMaBP; }
            set { SetPropertyValue<string>(nameof(MaBP), ref fMaBP, value); }
        }
        string fTenBP;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên bộ phận")]
        public string TenBP
        {
            get { return fTenBP; }
            set { SetPropertyValue<string>(nameof(TenBP), ref fTenBP, value); }
        }
        QuanLy fMaQL;
        [Size(10)]
        [Association(@"BoPhanReferencesQuanLy")]
        [DevExpress.Xpo.DisplayName(@"Mã quản lý")]
        public QuanLy MaQL
        {
            get { return fMaQL; }
            set { SetPropertyValue<QuanLy>(nameof(MaQL), ref fMaQL, value); }
        }
        [Association(@"NhanVienReferencesBoPhan")]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>(nameof(NhanViens)); } }
    }

}
