//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class CaLamViec : XPLiteObject
    {
        string fMaCa;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã ca làm")]
        public string MaCa
        {
            get { return fMaCa; }
            set { SetPropertyValue<string>(nameof(MaCa), ref fMaCa, value); }
        }
        string fTenCa;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên ca làm")]
        public string TenCa
        {
            get { return fTenCa; }
            set { SetPropertyValue<string>(nameof(TenCa), ref fTenCa, value); }
        }
        string fThoiGian;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Thời gian làm")]
        public string ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<string>(nameof(ThoiGian), ref fThoiGian, value); }
        }
        [Association(@"NhanVienReferencesCaLamViec")]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>(nameof(NhanViens)); } }
    }

}
