//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class ChiTietHD : XPLiteObject
    {
        string fMaChiTietHD;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã chi tiết hóa đơn")]
        public string MaChiTietHD
        {
            get { return fMaChiTietHD; }
            set { SetPropertyValue<string>(nameof(MaChiTietHD), ref fMaChiTietHD, value); }
        }
        string fTenChiTietHD;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên chi tiết hóa đơn")]
        public string TenChiTietHD
        {
            get { return fTenChiTietHD; }
            set { SetPropertyValue<string>(nameof(TenChiTietHD), ref fTenChiTietHD, value); }
        }
        DateTime fNgayHD;
        [DevExpress.Xpo.DisplayName(@"Ngày lập hóa đơn")]
        public DateTime NgayHD
        {
            get { return fNgayHD; }
            set { SetPropertyValue<DateTime>(nameof(NgayHD), ref fNgayHD, value); }
        }
        int fDonGia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        public int DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<int>(nameof(DonGia), ref fDonGia, value); }
        }
        int fSoluong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public int Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<int>(nameof(Soluong), ref fSoluong, value); }
        }
        SanPham fMaSP;
        [Size(10)]
        [Association(@"ChiTietHDReferencesSanPham")]
        [DevExpress.Xpo.DisplayName(@"Mã sản phẩm")]
        public SanPham MaSP
        {
            get { return fMaSP; }
            set
            {
                if (SetPropertyValue<SanPham>(nameof(MaSP), ref fMaSP, value)
                    && value != null && !IsLoading)
                    DonGia = value.DonGia;
            }
        }
        [Association(@"HoaDonReferencesChiTietHD")]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
        [Association(@"KhoHangReferencesChiTietHD")]
        public XPCollection<KhoHang> KhoHangs { get { return GetCollection<KhoHang>(nameof(KhoHangs)); } }
    }

}
