//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class DaiLy : XPLiteObject
    {
        string fMaDL;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã đại lý")]
        public string MaDL
        {
            get { return fMaDL; }
            set { SetPropertyValue<string>(nameof(MaDL), ref fMaDL, value); }
        }
        string fTenDL;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên đại lý")]
        public string TenDL
        {
            get { return fTenDL; }
            set { SetPropertyValue<string>(nameof(TenDL), ref fTenDL, value); }
        }
        string fDiaChi;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fSDT;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        QuanLy fMaQL;
        [Size(10)]
        [Association(@"DaiLyReferencesQuanLy")]
        [DevExpress.Xpo.DisplayName(@"Mã quản lý")]
        public QuanLy MaQL
        {
            get { return fMaQL; }
            set { SetPropertyValue<QuanLy>(nameof(MaQL), ref fMaQL, value); }
        }
        [Association(@"PhieuNhapReferencesDaiLy")]
        public XPCollection<PhieuNhap> PhieuNhaps { get { return GetCollection<PhieuNhap>(nameof(PhieuNhaps)); } }
    }

}
