//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class HoaDon : XPLiteObject
    {
        string fMaHD;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã hóa đơn")]
        public string MaHD
        {
            get { return fMaHD; }
            set { SetPropertyValue<string>(nameof(MaHD), ref fMaHD, value); }
        }
        string fTenHD;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên hóa đơn")]
        public string TenHD
        {
            get { return fTenHD; }
            set { SetPropertyValue<string>(nameof(TenHD), ref fTenHD, value); }
        }
        DateTime fNgayHD;
        [DevExpress.Xpo.DisplayName(@"Ngày hóa đơn")]
        public DateTime NgayHD
        {
            get { return fNgayHD; }
            set { SetPropertyValue<DateTime>(nameof(NgayHD), ref fNgayHD, value); }
        }
        int fSoLuong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        int fDonGia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        public int DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<int>(nameof(DonGia), ref fDonGia, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Tổng tiền")]
        public int TongTien
        {
            get
            {
                return DonGia * SoLuong;
            }
        }
        NhanVien fMaNV;
        [Size(10)]
        [Association(@"HoaDonReferencesNhanVien")]
        [DevExpress.Xpo.DisplayName(@"Mã nhân viên")]
        public NhanVien MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<NhanVien>(nameof(MaNV), ref fMaNV, value); }
        }
        Khach fMaKH;
        [Size(10)]
        [Association(@"HoaDonReferencesKhach")]
        [DevExpress.Xpo.DisplayName(@"Mã khách hàng")]
        public Khach MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<Khach>(nameof(MaKH), ref fMaKH, value); }
        }
        ChiTietHD fMaChiTietHD;
        [Size(10)]
        [Association(@"HoaDonReferencesChiTietHD")]
        [DevExpress.Xpo.DisplayName(@"Mã chi tiết hóa đơn")]
        public ChiTietHD MaChiTietHD
        {
            get { return fMaChiTietHD; }
            set
            {
                if (SetPropertyValue<ChiTietHD>(nameof(MaChiTietHD), ref fMaChiTietHD, value)
                    && value != null && !IsLoading)
                    DonGia = value.DonGia;
            }
        }
        [Association(@"PhieuXuatReferencesHoaDon")]
        public XPCollection<PhieuXuat> PhieuXuats { get { return GetCollection<PhieuXuat>(nameof(PhieuXuats)); } }
    }

}
