//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class Khach : XPLiteObject
    {
        string fMaKH;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã khách hàng")]
        public string MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<string>(nameof(MaKH), ref fMaKH, value); }
        }
        string fTenKH;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên khách hàng")]
        public string TenKH
        {
            get { return fTenKH; }
            set { SetPropertyValue<string>(nameof(TenKH), ref fTenKH, value); }
        }
        string fDiaChi;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fSDT;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        NhanVien fMaNV;
        [Size(10)]
        [Association(@"KhachReferencesNhanVien")]
        [DevExpress.Xpo.DisplayName(@"Mã nhân viên")]
        public NhanVien MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<NhanVien>(nameof(MaNV), ref fMaNV, value); }
        }
        [Association(@"HoaDonReferencesKhach")]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
        [Association(@"SanPhamReferencesKhach")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
