//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class KhoHang : XPLiteObject
    {
        string fMaKho;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã kho")]
        public string MaKho
        {
            get { return fMaKho; }
            set { SetPropertyValue<string>(nameof(MaKho), ref fMaKho, value); }
        }
        string fTenKho;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên kho")]
        public string TenKho
        {
            get { return fTenKho; }
            set { SetPropertyValue<string>(nameof(TenKho), ref fTenKho, value); }
        }
        int fSoLuong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        string fViTriSP;
        [DevExpress.Xpo.DisplayName(@"Vị trí sản phẩm")]
        public string ViTriSP
        {
            get { return fViTriSP; }
            set { SetPropertyValue<string>(nameof(ViTriSP), ref fViTriSP, value); }
        }
        ChiTietHD fMaChiTietHD;
        [Size(10)]
        [Association(@"KhoHangReferencesChiTietHD")]
        [DevExpress.Xpo.DisplayName(@"Mã chi tiết hóa đơn")]
        public ChiTietHD MaChiTietHD
        {
            get { return fMaChiTietHD; }
            set
            {
                if (SetPropertyValue<ChiTietHD>(nameof(MaChiTietHD), ref fMaChiTietHD, value)
                    && value != null && !IsLoading)
                    SoLuongTong = SoLuong - value.Soluong;
            }
        }
        PhieuNhap fMaNhap;
        [Association(@"KhoHangReferencesPhieuNhap")]
        [DevExpress.Xpo.DisplayName(@"Mã nhập")]
        public PhieuNhap MaNhap
        {
            get { return fMaNhap; }
            set
            {
                if (SetPropertyValue<PhieuNhap>(nameof(MaNhap), ref fMaNhap, value)
                    && value != null && !IsLoading)
                    SoLuong = value.SoLuong;
            }
        }
        int fSoLuongTong;
        [DevExpress.Xpo.DisplayName(@"Số Lượng Còn Lại")]
        public int SoLuongTong
        {
            get { return fSoLuongTong; }
            set { SetPropertyValue<int>(nameof(SoLuongTong), ref fSoLuongTong, value); }
        }
    }

}
