//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class LoaiSanPham : XPLiteObject
    {
        string fMaLoai;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã loại sản phẩm")]
        public string MaLoai
        {
            get { return fMaLoai; }
            set { SetPropertyValue<string>(nameof(MaLoai), ref fMaLoai, value); }
        }
        string fTenLoai;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên loại sản phẩm")]
        public string TenLoai
        {
            get { return fTenLoai; }
            set { SetPropertyValue<string>(nameof(TenLoai), ref fTenLoai, value); }
        }
        [Association(@"SanPhamReferencesLoaiSanPham")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
