//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class NhanVien : XPLiteObject
    {
        string fMaNV;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã nhân viên")]
        public string MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<string>(nameof(MaNV), ref fMaNV, value); }
        }
        string fTenNV;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên nhân viên")]
        public string TenNV
        {
            get { return fTenNV; }
            set { SetPropertyValue<string>(nameof(TenNV), ref fTenNV, value); }
        }
        string fDiaChi;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fSDT;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        string fGioiTinh;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Giới tính")]
        public string GioiTinh
        {
            get { return fGioiTinh; }
            set { SetPropertyValue<string>(nameof(GioiTinh), ref fGioiTinh, value); }
        }
        QuanLy fMaQL;
        [Size(10)]
        [Association(@"NhanVienReferencesQuanLy")]
        [DevExpress.Xpo.DisplayName(@"Mã quản lý")]
        public QuanLy MaQL
        {
            get { return fMaQL; }
            set { SetPropertyValue<QuanLy>(nameof(MaQL), ref fMaQL, value); }
        }
        CaLamViec fMaca;
        [Size(10)]
        [Association(@"NhanVienReferencesCaLamViec")]
        [DevExpress.Xpo.DisplayName(@"Mã ca làm")]
        public CaLamViec Maca
        {
            get { return fMaca; }
            set { SetPropertyValue<CaLamViec>(nameof(Maca), ref fMaca, value); }
        }
        BoPhan fMaBP;
        [Size(10)]
        [Association(@"NhanVienReferencesBoPhan")]
        [DevExpress.Xpo.DisplayName(@"Mã bộ phận")]
        public BoPhan MaBP
        {
            get { return fMaBP; }
            set { SetPropertyValue<BoPhan>(nameof(MaBP), ref fMaBP, value); }
        }
        [Association(@"HoaDonReferencesNhanVien")]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
        [Association(@"KhachReferencesNhanVien")]
        public XPCollection<Khach> Khaches { get { return GetCollection<Khach>(nameof(Khaches)); } }
        [Association(@"PhieuNhapReferencesNhanVien")]
        public XPCollection<PhieuNhap> PhieuNhaps { get { return GetCollection<PhieuNhap>(nameof(PhieuNhaps)); } }
    }

}
