//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class PhieuXuat : XPLiteObject
    {
        string fMaXuat;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã phiếu xuất")]
        public string MaXuat
        {
            get { return fMaXuat; }
            set { SetPropertyValue<string>(nameof(MaXuat), ref fMaXuat, value); }
        }
        string fTenXuat;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên phiếu xuất")]
        public string TenXuat
        {
            get { return fTenXuat; }
            set { SetPropertyValue<string>(nameof(TenXuat), ref fTenXuat, value); }
        }
        int fSoLuong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        int fDonGia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        public int DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<int>(nameof(DonGia), ref fDonGia, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        public int ThanhTien
        {
            get
            {
                return SoLuong * DonGia;
            }
        }
        DateTime fNgayNhap;
        [DevExpress.Xpo.DisplayName(@"Ngày nhập")]
        public DateTime NgayNhap
        {
            get { return fNgayNhap; }
            set { SetPropertyValue<DateTime>(nameof(NgayNhap), ref fNgayNhap, value); }
        }
        HoaDon fMaHD;
        [Size(10)]
        [Association(@"PhieuXuatReferencesHoaDon")]
        [DevExpress.Xpo.DisplayName(@"Mã hóa đơn")]
        public HoaDon MaHD
        {
            get { return fMaHD; }
            set
            {
                if (SetPropertyValue<HoaDon>(nameof(MaHD), ref fMaHD, value)
                   && value != null && !IsLoading)
                    DonGia = value.DonGia;
            }
        }
        [Association(@"ThuChiReferencesPhieuXuat")]
        public XPCollection<ThuChi> ThuChis { get { return GetCollection<ThuChi>(nameof(ThuChis)); } }
    }

}
