//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class QuanLy : XPLiteObject
    {
        string fMaQL;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã quản lý")]
        public string MaQL
        {
            get { return fMaQL; }
            set { SetPropertyValue<string>(nameof(MaQL), ref fMaQL, value); }
        }
        string fTenQL;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên quản lý")]
        public string TenQL
        {
            get { return fTenQL; }
            set { SetPropertyValue<string>(nameof(TenQL), ref fTenQL, value); }
        }
        string fDiaChi;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fSDT;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        string fGioiTinh;
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Giới tính")]
        public string GioiTinh
        {
            get { return fGioiTinh; }
            set { SetPropertyValue<string>(nameof(GioiTinh), ref fGioiTinh, value); }
        }
        [Association(@"BoPhanReferencesQuanLy")]
        public XPCollection<BoPhan> BoPhans { get { return GetCollection<BoPhan>(nameof(BoPhans)); } }
        [Association(@"DaiLyReferencesQuanLy")]
        public XPCollection<DaiLy> DaiLies { get { return GetCollection<DaiLy>(nameof(DaiLies)); } }
        [Association(@"NhanVienReferencesQuanLy")]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>(nameof(NhanViens)); } }
        [Association(@"ThuChiReferencesQuanLy")]
        public XPCollection<ThuChi> ThuChis { get { return GetCollection<ThuChi>(nameof(ThuChis)); } }
    }

}
