//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DANHOM.Module.QLCuaHangPB
{

    public partial class ThuChi : XPLiteObject
    {
        string fMaTC;
        [Key]
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"Mã thu chi")]
        public string MaTC
        {
            get { return fMaTC; }
            set { SetPropertyValue<string>(nameof(MaTC), ref fMaTC, value); }
        }
        string fTenTC;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên thu chi")]
        public string TenTC
        {
            get { return fTenTC; }
            set { SetPropertyValue<string>(nameof(TenTC), ref fTenTC, value); }
        }
        string fLoaiTC;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Loai thu chi")]
        public string LoaiTC
        {
            get { return fLoaiTC; }
            set { SetPropertyValue<string>(nameof(LoaiTC), ref fLoaiTC, value); }
        }
        string fGhiChu;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Ghi chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>(nameof(GhiChu), ref fGhiChu, value); }
        }
        int fTongTienN;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tổng tiền nhập")]
        public int TongTienN
        {
            get { return fTongTienN; }
            set { SetPropertyValue<int>(nameof(TongTienN), ref fTongTienN, value); }
        }
        int fTongTienX;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tổng tiền xuất")]
        public int TongTienX
        {
            get { return fTongTienX; }
            set { SetPropertyValue<int>(nameof(TongTienX), ref fTongTienX, value); }
        }
        public int TienThuChi
        {
            get
            {
                return TongTienX - TongTienN;
            }
        }
        PhieuXuat fMaXuat;
        [Size(10)]
        [Association(@"ThuChiReferencesPhieuXuat")]
        [DevExpress.Xpo.DisplayName(@"Mã phiếu xuất")]
        public PhieuXuat MaXuat
        {
            get { return fMaXuat; }
            set
            {
                if (SetPropertyValue<PhieuXuat>(nameof(MaXuat), ref fMaXuat, value)
                    && value != null && !IsLoading)
                    TongTienX = value.ThanhTien;
            }
        }
        PhieuNhap fMaNhap;
        [Size(10)]
        [Association(@"ThuChiReferencesPhieuNhap")]
        [DevExpress.Xpo.DisplayName(@"Mã phiếu nhập")]
        public PhieuNhap MaNhap
        {
            get { return fMaNhap; }
            set
            {
                if (SetPropertyValue<PhieuNhap>(nameof(MaNhap), ref fMaNhap, value)
                    && value != null && !IsLoading)
                    TongTienN = value.ThanhTien;
            }
        }
        QuanLy fMaQL;
        [Size(10)]
        [Association(@"ThuChiReferencesQuanLy")]
        [DevExpress.Xpo.DisplayName(@"Mã quản lý")]
        public QuanLy MaQL
        {
            get { return fMaQL; }
            set { SetPropertyValue<QuanLy>(nameof(MaQL), ref fMaQL, value); }
        }
    }

}
